set -g status-style 'bg=#1A1A1A,fg=#D0FF1D'
set -g status-left ' #S '
set -g status-right '#[fg=#D0FF1D,bg=#404040] #(echo "#{pane_current_path}" | sed "s|^$HOME|~|") #[fg=#D0FF1D,bg=#808080] #(git -C "#{pane_current_path}" branch --show-current 2>/dev/null) '
set -g status-right-length 256
set -g status-interval 5
set -g window-status-format ' #I:#W '
set -g window-status-current-format '#[fg=#000000,bg=#D0FF1D] #I:#W '

unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind C-a last-window

bind C-r source-file ~/.tmux.conf

bind c new-window -c '#{pane_current_path}'
bind s split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind < resize-pane -L 1
bind > resize-pane -R 1
bind - resize-pane -D 1
bind + resize-pane -U 1
bind : command-prompt
setw -g mode-keys vi

set -g base-index 1
setw -g pane-base-index 1

set -g monitor-bell on
set -g bell-action any
set -g visual-bell off
